--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Sprite_6
local Sprite_6 = cc.Sprite:create("Res/Tollgate/1001/BG1-hd.png")
Sprite_6:setName("Sprite_6")
Sprite_6:setTag(28)
Sprite_6:setCascadeColorEnabled(true)
Sprite_6:setCascadeOpacityEnabled(true)
Sprite_6:setAnchorPoint(0.0000, 0.0000)
Sprite_6:setPosition(-0.0001, 0.0000)
Sprite_6:setScaleX(0.6497)
Sprite_6:setScaleY(0.6514)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_6)
layout:setPositionPercentX(0.0000)
layout:setPercentWidth(1.5385)
layout:setPercentHeight(1.5385)
layout:setSize(cc.size(960.0000, 640.0000))
layout:setLeftMargin(-0.0001)
layout:setRightMargin(-335.9999)
layout:setTopMargin(-224.0000)
Scene:addChild(Sprite_6)

--Create Sprite_8
local Sprite_8 = cc.Sprite:create("Res/Tollgate/1001/BG-hd.png")
Sprite_8:setName("Sprite_8")
Sprite_8:setTag(30)
Sprite_8:setCascadeColorEnabled(true)
Sprite_8:setCascadeOpacityEnabled(true)
Sprite_8:setAnchorPoint(0.0000, 1.0000)
Sprite_8:setScaleX(0.6911)
Sprite_8:setScaleY(0.6503)
Sprite_8:setRotationSkewX(-90.0000)
Sprite_8:setRotationSkewY(-90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_8)
layout:setPercentWidth(0.7692)
layout:setPercentHeight(2.4615)
layout:setSize(cc.size(480.0000, 1024.0000))
layout:setRightMargin(144.0000)
layout:setTopMargin(416.0000)
layout:setBottomMargin(-1024.0000)
Scene:addChild(Sprite_8)

--Create Btn_0_0
local Btn_0_0 = ccui.Button:create()
Btn_0_0:ignoreContentAdaptWithSize(false)
Btn_0_0:loadTextureNormal("Default/Button_Normal.png",0)
Btn_0_0:loadTexturePressed("Default/Button_Press.png",0)
Btn_0_0:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_0_0:setTitleFontSize(14)
Btn_0_0:setTitleColor(cc.c3b(65, 65, 70))
Btn_0_0:setLayoutComponentEnabled(true)
Btn_0_0:setName("Btn_0_0")
Btn_0_0:setTag(17)
Btn_0_0:setCascadeColorEnabled(true)
Btn_0_0:setCascadeOpacityEnabled(true)
Btn_0_0:setPosition(26.0000, 26.0000)
Btn_0_0:setOpacity(115)
Btn_0_0:setColor(cc.c3b(255, 0, 0))
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_0_0)
layout:setPositionPercentX(0.0417)
layout:setPositionPercentY(0.0625)
layout:setPercentWidth(0.0833)
layout:setPercentHeight(0.1250)
layout:setSize(cc.size(52.0000, 52.0000))
layout:setRightMargin(572.0000)
layout:setTopMargin(364.0000)
Scene:addChild(Btn_0_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

