--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Btn_LeftPage
local Btn_LeftPage = ccui.Button:create()
Btn_LeftPage:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene1-hd.plist")
Btn_LeftPage:loadTextureNormal("theme_pointleft_normal.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene1-hd.plist")
Btn_LeftPage:loadTexturePressed("theme_pointleft_pressed.png",1)
Btn_LeftPage:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_LeftPage:setTitleFontSize(14)
Btn_LeftPage:setTitleColor(cc.c3b(65, 65, 70))
Btn_LeftPage:setLayoutComponentEnabled(true)
Btn_LeftPage:setName("Btn_LeftPage")
Btn_LeftPage:setTag(17)
Btn_LeftPage:setCascadeColorEnabled(true)
Btn_LeftPage:setCascadeOpacityEnabled(true)
Btn_LeftPage:setVisible(false)
Btn_LeftPage:setPosition(61.2073, 208.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_LeftPage)
layout:setPositionPercentX(0.0981)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.1563)
layout:setSize(cc.size(65.0000, 65.0000))
layout:setLeftMargin(28.7073)
layout:setRightMargin(530.2927)
layout:setTopMargin(175.5000)
layout:setBottomMargin(175.5000)
Scene:addChild(Btn_LeftPage)

--Create Btn_RightPage
local Btn_RightPage = ccui.Button:create()
Btn_RightPage:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene1-hd.plist")
Btn_RightPage:loadTextureNormal("theme_pointright_normal.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene1-hd.plist")
Btn_RightPage:loadTexturePressed("theme_pointright_pressed.png",1)
Btn_RightPage:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_RightPage:setTitleFontSize(14)
Btn_RightPage:setTitleColor(cc.c3b(65, 65, 70))
Btn_RightPage:setLayoutComponentEnabled(true)
Btn_RightPage:setName("Btn_RightPage")
Btn_RightPage:setTag(18)
Btn_RightPage:setCascadeColorEnabled(true)
Btn_RightPage:setCascadeOpacityEnabled(true)
Btn_RightPage:setVisible(false)
Btn_RightPage:setPosition(563.5191, 208.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_RightPage)
layout:setPositionPercentX(0.9031)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1042)
layout:setPercentHeight(0.1563)
layout:setSize(cc.size(65.0000, 65.0000))
layout:setLeftMargin(531.0191)
layout:setRightMargin(27.9809)
layout:setTopMargin(175.5000)
layout:setBottomMargin(175.5000)
Scene:addChild(Btn_RightPage)

--Create PageView_Tollgate
local PageView_Tollgate = ccui.PageView:create()
PageView_Tollgate:ignoreContentAdaptWithSize(false)
PageView_Tollgate:setClippingEnabled(true)
PageView_Tollgate:setBackGroundColorType(1)
PageView_Tollgate:setBackGroundColor(cc.c3b(150, 150, 100))
PageView_Tollgate:setBackGroundColorOpacity(0)
PageView_Tollgate:setLayoutComponentEnabled(true)
PageView_Tollgate:setName("PageView_Tollgate")
PageView_Tollgate:setTag(12)
PageView_Tollgate:setCascadeColorEnabled(true)
PageView_Tollgate:setCascadeOpacityEnabled(true)
PageView_Tollgate:setPosition(0.0000, 42.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(PageView_Tollgate)
layout:setPositionPercentY(0.1010)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.7692)
layout:setSize(cc.size(624.0000, 320.0000))
layout:setTopMargin(54.0000)
layout:setBottomMargin(42.0000)
Scene:addChild(PageView_Tollgate)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene2-hd.plist")
Panel_1:setBackGroundImage("theme_pack01.png",1)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor(cc.c3b(150, 200, 255))
Panel_1:setBackGroundColorOpacity(0)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(13)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(624.0000, 320.0000))
PageView_Tollgate:addPage(Panel_1)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene2-hd.plist")
Panel_2:setBackGroundImage("theme_pack02.png",1)
Panel_2:setBackGroundColorType(1)
Panel_2:setBackGroundColor(cc.c3b(150, 200, 255))
Panel_2:setBackGroundColorOpacity(0)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(15)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setPosition(624.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentX(1.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(624.0000, 320.0000))
layout:setLeftMargin(624.0000)
layout:setRightMargin(-624.0000)
PageView_Tollgate:addPage(Panel_2)

--Create Panel_3
local Panel_3 = ccui.Layout:create()
Panel_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/themescene2-hd.plist")
Panel_3:setBackGroundImage("theme_pack03.png",1)
Panel_3:setBackGroundColorType(1)
Panel_3:setBackGroundColor(cc.c3b(150, 200, 255))
Panel_3:setBackGroundColorOpacity(0)
Panel_3:setTouchEnabled(true);
Panel_3:setLayoutComponentEnabled(true)
Panel_3:setName("Panel_3")
Panel_3:setTag(16)
Panel_3:setCascadeColorEnabled(true)
Panel_3:setCascadeOpacityEnabled(true)
Panel_3:setPosition(1248.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_3)
layout:setPositionPercentX(2.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(624.0000, 320.0000))
layout:setLeftMargin(1248.0000)
layout:setRightMargin(-1248.0000)
PageView_Tollgate:addPage(Panel_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

