--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Pic_Bg
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
local Pic_Bg = cc.Sprite:createWithSpriteFrameName("mainbg.png")
Pic_Bg:setName("Pic_Bg")
Pic_Bg:setTag(2)
Pic_Bg:setCascadeColorEnabled(true)
Pic_Bg:setCascadeOpacityEnabled(true)
Pic_Bg:setPosition(312.0000, 208.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_Bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(624.0000, 416.0000))
Scene:addChild(Pic_Bg)

--Create Pic_CarrotRight
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
local Pic_CarrotRight = cc.Sprite:createWithSpriteFrameName("leaf-3.png")
Pic_CarrotRight:setName("Pic_CarrotRight")
Pic_CarrotRight:setTag(11)
Pic_CarrotRight:setCascadeColorEnabled(true)
Pic_CarrotRight:setCascadeOpacityEnabled(true)
Pic_CarrotRight:setPosition(357.3902, 312.8087)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_CarrotRight)
layout:setPositionPercentX(0.5727)
layout:setPositionPercentY(0.7519)
layout:setPercentWidth(0.1250)
layout:setPercentHeight(0.2043)
layout:setSize(cc.size(78.0000, 85.0000))
layout:setLeftMargin(318.3902)
layout:setRightMargin(227.6098)
layout:setTopMargin(60.6913)
layout:setBottomMargin(270.3087)
Pic_Bg:addChild(Pic_CarrotRight)

--Create Pic_CarrotLeft
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
local Pic_CarrotLeft = cc.Sprite:createWithSpriteFrameName("leaf-1.png")
Pic_CarrotLeft:setName("Pic_CarrotLeft")
Pic_CarrotLeft:setTag(9)
Pic_CarrotLeft:setCascadeColorEnabled(true)
Pic_CarrotLeft:setCascadeOpacityEnabled(true)
Pic_CarrotLeft:setPosition(265.0153, 316.2147)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_CarrotLeft)
layout:setPositionPercentX(0.4247)
layout:setPositionPercentY(0.7601)
layout:setPercentWidth(0.1362)
layout:setPercentHeight(0.2188)
layout:setSize(cc.size(85.0000, 91.0000))
layout:setLeftMargin(222.5153)
layout:setRightMargin(316.4847)
layout:setTopMargin(54.2853)
layout:setBottomMargin(270.7147)
Pic_Bg:addChild(Pic_CarrotLeft)

--Create Pic_CarrotMiddle
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
local Pic_CarrotMiddle = cc.Sprite:createWithSpriteFrameName("leaf-2.png")
Pic_CarrotMiddle:setName("Pic_CarrotMiddle")
Pic_CarrotMiddle:setTag(12)
Pic_CarrotMiddle:setCascadeColorEnabled(true)
Pic_CarrotMiddle:setCascadeOpacityEnabled(true)
Pic_CarrotMiddle:setPosition(309.4478, 327.2142)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_CarrotMiddle)
layout:setPositionPercentX(0.4959)
layout:setPositionPercentY(0.7866)
layout:setPercentWidth(0.1875)
layout:setPercentHeight(0.2500)
layout:setSize(cc.size(117.0000, 104.0000))
layout:setLeftMargin(250.9478)
layout:setRightMargin(256.0522)
layout:setTopMargin(36.7858)
layout:setBottomMargin(275.2142)
Pic_Bg:addChild(Pic_CarrotMiddle)

--Create Pic_Carrot
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
local Pic_Carrot = cc.Sprite:createWithSpriteFrameName("carrot.png")
Pic_Carrot:setName("Pic_Carrot")
Pic_Carrot:setTag(3)
Pic_Carrot:setCascadeColorEnabled(true)
Pic_Carrot:setCascadeOpacityEnabled(true)
Pic_Carrot:setPosition(310.4637, 247.7124)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_Carrot)
layout:setPositionPercentX(0.4975)
layout:setPositionPercentY(0.5955)
layout:setPercentWidth(0.2292)
layout:setPercentHeight(0.3125)
layout:setSize(cc.size(143.0000, 130.0000))
layout:setLeftMargin(238.9637)
layout:setRightMargin(242.0363)
layout:setTopMargin(103.2876)
layout:setBottomMargin(182.7124)
Pic_Bg:addChild(Pic_Carrot)

--Create Pic_Title
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
local Pic_Title = cc.Sprite:createWithSpriteFrameName("mainbg_CN.png")
Pic_Title:setName("Pic_Title")
Pic_Title:setTag(4)
Pic_Title:setCascadeColorEnabled(true)
Pic_Title:setCascadeOpacityEnabled(true)
Pic_Title:setPosition(312.0000, 208.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_Title)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(624.0000, 416.0000))
Pic_Bg:addChild(Pic_Title)

--Create Btn_Advanture
local Btn_Advanture = ccui.Button:create()
Btn_Advanture:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
Btn_Advanture:loadTextureNormal("btn_adventure_normal_CN.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
Btn_Advanture:loadTexturePressed("btn_adventure_pressed_CN.png",1)
Btn_Advanture:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_Advanture:setTitleFontSize(14)
Btn_Advanture:setTitleColor(cc.c3b(65, 65, 70))
Btn_Advanture:setLayoutComponentEnabled(true)
Btn_Advanture:setName("Btn_Advanture")
Btn_Advanture:setTag(5)
Btn_Advanture:setCascadeColorEnabled(true)
Btn_Advanture:setCascadeOpacityEnabled(true)
Btn_Advanture:setPosition(112.4999, 52.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Advanture)
layout:setPositionPercentX(0.1803)
layout:setPositionPercentY(0.1250)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.2500)
layout:setSize(cc.size(195.0000, 104.0000))
layout:setLeftMargin(14.9999)
layout:setRightMargin(414.0001)
layout:setTopMargin(312.0000)
Scene:addChild(Btn_Advanture)

--Create Btn_Boss
local Btn_Boss = ccui.Button:create()
Btn_Boss:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
Btn_Boss:loadTextureNormal("btn_boss_normal_CN.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
Btn_Boss:loadTexturePressed("btn_boss_pressed_CN.png",1)
Btn_Boss:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_Boss:setTitleFontSize(14)
Btn_Boss:setTitleColor(cc.c3b(65, 65, 70))
Btn_Boss:setLayoutComponentEnabled(true)
Btn_Boss:setName("Btn_Boss")
Btn_Boss:setTag(6)
Btn_Boss:setCascadeColorEnabled(true)
Btn_Boss:setCascadeOpacityEnabled(true)
Btn_Boss:setPosition(312.0000, 52.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Boss)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1250)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.2500)
layout:setSize(cc.size(195.0000, 104.0000))
layout:setLeftMargin(214.5000)
layout:setRightMargin(214.5000)
layout:setTopMargin(312.0000)
Scene:addChild(Btn_Boss)

--Create Btn_Nest
local Btn_Nest = ccui.Button:create()
Btn_Nest:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
Btn_Nest:loadTextureNormal("btn_nest_normal_CN.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/scene/mainscene1-hd.plist")
Btn_Nest:loadTexturePressed("btn_nest_pressed_CN.png",1)
Btn_Nest:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_Nest:setTitleFontSize(14)
Btn_Nest:setTitleColor(cc.c3b(65, 65, 70))
Btn_Nest:setLayoutComponentEnabled(true)
Btn_Nest:setName("Btn_Nest")
Btn_Nest:setTag(8)
Btn_Nest:setCascadeColorEnabled(true)
Btn_Nest:setCascadeOpacityEnabled(true)
Btn_Nest:setPosition(511.4999, 52.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Nest)
layout:setPositionPercentX(0.8197)
layout:setPositionPercentY(0.1250)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.2500)
layout:setSize(cc.size(195.0000, 104.0000))
layout:setLeftMargin(413.9999)
layout:setRightMargin(15.0001)
layout:setTopMargin(312.0000)
Scene:addChild(Btn_Nest)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

