--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Pic_MenuBg
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/Items/Items02-hd.plist")
local Pic_MenuBg = cc.Sprite:createWithSpriteFrameName("MenuBG.png")
Pic_MenuBg:setName("Pic_MenuBg")
Pic_MenuBg:setTag(20)
Pic_MenuBg:setCascadeColorEnabled(true)
Pic_MenuBg:setCascadeOpacityEnabled(true)
Pic_MenuBg:setPosition(312.0000, 390.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_MenuBg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9375)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1250)
layout:setSize(cc.size(624.0000, 52.0000))
layout:setBottomMargin(364.0000)
Scene:addChild(Pic_MenuBg)

--Create Pic_WaveBg
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/Items/Items02-hd.plist")
local Pic_WaveBg = cc.Sprite:createWithSpriteFrameName("MenuCenter_01_CN.png")
Pic_WaveBg:setName("Pic_WaveBg")
Pic_WaveBg:setTag(21)
Pic_WaveBg:setCascadeColorEnabled(true)
Pic_WaveBg:setCascadeOpacityEnabled(true)
Pic_WaveBg:setPosition(299.0000, 389.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Pic_WaveBg)
layout:setPositionPercentX(0.4792)
layout:setPositionPercentY(0.9351)
layout:setPercentWidth(0.3125)
layout:setPercentHeight(0.1250)
layout:setSize(cc.size(195.0000, 52.0000))
layout:setLeftMargin(201.5000)
layout:setRightMargin(227.5000)
layout:setTopMargin(1.0000)
layout:setBottomMargin(363.0000)
Scene:addChild(Pic_WaveBg)

--Create Btn_Speed
local Btn_Speed = ccui.Button:create()
Btn_Speed:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/Items/Items02-hd.plist")
Btn_Speed:loadTextureNormal("speed11.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/Items/Items02-hd.plist")
Btn_Speed:loadTexturePressed("speed12.png",1)
Btn_Speed:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_Speed:setTitleFontSize(14)
Btn_Speed:setTitleColor(cc.c3b(65, 65, 70))
Btn_Speed:setLayoutComponentEnabled(true)
Btn_Speed:setName("Btn_Speed")
Btn_Speed:setTag(22)
Btn_Speed:setCascadeColorEnabled(true)
Btn_Speed:setCascadeOpacityEnabled(true)
Btn_Speed:setPosition(424.0000, 390.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Speed)
layout:setPositionPercentX(0.6795)
layout:setPositionPercentY(0.9375)
layout:setPercentWidth(0.1154)
layout:setPercentHeight(0.1250)
layout:setSize(cc.size(72.0000, 52.0000))
layout:setLeftMargin(388.0000)
layout:setRightMargin(164.0000)
layout:setBottomMargin(364.0000)
Scene:addChild(Btn_Speed)

--Create Btn_Stop
local Btn_Stop = ccui.Button:create()
Btn_Stop:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/Items/Items02-hd.plist")
Btn_Stop:loadTextureNormal("pause01.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Res/Items/Items02-hd.plist")
Btn_Stop:loadTexturePressed("pause02.png",1)
Btn_Stop:loadTextureDisabled("Default/Button_Disable.png",0)
Btn_Stop:setTitleFontSize(14)
Btn_Stop:setTitleColor(cc.c3b(65, 65, 70))
Btn_Stop:setLayoutComponentEnabled(true)
Btn_Stop:setName("Btn_Stop")
Btn_Stop:setTag(23)
Btn_Stop:setCascadeColorEnabled(true)
Btn_Stop:setCascadeOpacityEnabled(true)
Btn_Stop:setPosition(504.0000, 390.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_Stop)
layout:setPositionPercentX(0.8077)
layout:setPositionPercentY(0.9375)
layout:setPercentWidth(0.0625)
layout:setPercentHeight(0.1250)
layout:setSize(cc.size(39.0000, 52.0000))
layout:setLeftMargin(484.5000)
layout:setRightMargin(100.5000)
layout:setBottomMargin(364.0000)
Scene:addChild(Btn_Stop)

--Create AtlasLabel_Gold
local AtlasLabel_Gold = ccui.TextAtlas:create([[1234]],
													"Res/Items/numwhite.png",
													13,
													26,
													".")
AtlasLabel_Gold:setLayoutComponentEnabled(true)
AtlasLabel_Gold:setName("AtlasLabel_Gold")
AtlasLabel_Gold:setTag(24)
AtlasLabel_Gold:setCascadeColorEnabled(true)
AtlasLabel_Gold:setCascadeOpacityEnabled(true)
AtlasLabel_Gold:setAnchorPoint(0.0000, 0.5000)
AtlasLabel_Gold:setPosition(67.5000, 395.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_Gold)
layout:setPositionPercentX(0.1082)
layout:setPositionPercentY(0.9495)
layout:setPercentWidth(0.0833)
layout:setPercentHeight(0.0625)
layout:setSize(cc.size(52.0000, 26.0000))
layout:setLeftMargin(67.5000)
layout:setRightMargin(504.5000)
layout:setTopMargin(8.0000)
layout:setBottomMargin(382.0000)
Scene:addChild(AtlasLabel_Gold)

--Create AtlasLabel_WaveTens
local AtlasLabel_WaveTens = ccui.TextAtlas:create([[1]],
													"Res/Items/numyellow.png",
													26,
													24,
													".")
AtlasLabel_WaveTens:setLayoutComponentEnabled(true)
AtlasLabel_WaveTens:setName("AtlasLabel_WaveTens")
AtlasLabel_WaveTens:setTag(26)
AtlasLabel_WaveTens:setCascadeColorEnabled(true)
AtlasLabel_WaveTens:setCascadeOpacityEnabled(true)
AtlasLabel_WaveTens:setPosition(233.0000, 394.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_WaveTens)
layout:setPositionPercentX(0.3734)
layout:setPositionPercentY(0.9471)
layout:setPercentWidth(0.0417)
layout:setPercentHeight(0.0577)
layout:setSize(cc.size(26.0000, 24.0000))
layout:setLeftMargin(220.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(10.0000)
layout:setBottomMargin(382.0000)
Scene:addChild(AtlasLabel_WaveTens)

--Create AtlasLabel_WaveOnes
local AtlasLabel_WaveOnes = ccui.TextAtlas:create([[1]],
													"Res/Items/numyellow.png",
													26,
													24,
													".")
AtlasLabel_WaveOnes:setLayoutComponentEnabled(true)
AtlasLabel_WaveOnes:setName("AtlasLabel_WaveOnes")
AtlasLabel_WaveOnes:setTag(27)
AtlasLabel_WaveOnes:setCascadeColorEnabled(true)
AtlasLabel_WaveOnes:setCascadeOpacityEnabled(true)
AtlasLabel_WaveOnes:setPosition(262.0000, 394.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(AtlasLabel_WaveOnes)
layout:setPositionPercentX(0.4199)
layout:setPositionPercentY(0.9471)
layout:setPercentWidth(0.0417)
layout:setPercentHeight(0.0577)
layout:setSize(cc.size(26.0000, 24.0000))
layout:setLeftMargin(249.0000)
layout:setRightMargin(349.0000)
layout:setTopMargin(10.0000)
layout:setBottomMargin(382.0000)
Scene:addChild(AtlasLabel_WaveOnes)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

