local w_defines = {}
-- 格子类型
local GRIDTYPE_CANPUTTOWER = 1 -- 可放塔
local GRIDTYPE_HASPUTTOWER = 2 -- 已放塔
local GRIDTYPE_FORBIDDENPUT = 3 -- 禁止放塔
local GRIDTYPE_HASBLOCK = 4 -- 有可攻击阻挡
local GRIDTYPE_POINTBORN = 5 -- 怪物出生点
local GRIDTYPE_POINTPATH = 6 -- 怪物路径点
local GRIDTYPE_POINCARROT = 7 -- 萝卜点

w_defines.GRIDTYPE_CANPUTTOWER = GRIDTYPE_CANPUTTOWER
w_defines.GRIDTYPE_HASPUTTOWER = GRIDTYPE_HASPUTTOWER
w_defines.GRIDTYPE_FORBIDDENPUT = GRIDTYPE_FORBIDDENPUT
w_defines.GRIDTYPE_HASBLOCK = GRIDTYPE_HASBLOCK
w_defines.GRIDTYPE_POINTBORN = GRIDTYPE_POINTBORN
w_defines.GRIDTYPE_POINTPATH = GRIDTYPE_POINTPATH
w_defines.GRIDTYPE_POINCARROT = GRIDTYPE_POINCARROT
return w_defines